### PR TITLE
Addition of module GiftiLoader

### PR DESCRIPTION
**Pull request by mcespedes99**
I'm opening this PR to include my module GiftiLoder into this extension, as suggested by @lassoan. Refer to [this PR](https://github.com/Slicer/ExtensionsIndex/pull/1952) for more information. I added the corresponding directory for the module along with some minor updates to other files. I modified a bit the structure of the Docs folder to organize it a little bit as well. 

As this extension contains a C++ module, I need to compile Slicer to try it out, which I haven't done yet. I'll do it tomorrow morning and leave a comment here. If you want to test it as well, feel free to do it. Thanks for any feedback in advance.

### CODE REVIEW

**Comment by mcespedes99** [comment]
@lassoan just tested my changes by building the package. I didn't test the ACPC transform module cause I didn't touch it but it does show up. I tested my module and it seems to be working just fine. If we are not waiting for the whole itk thing to be solved, I think it should be good to go.

**Comment by mcespedes99** [comment]
@lassoan I was checking the thread from itk forum but I see that the itk package is not installed by default in Slicer as well. If you would like me to change from nibabel to itk, I can try it out but not sure if it's worth. Please let me know! Thanks

**Review by lassoan — CHANGES_REQUESTED** [review]
We can leave the reader as is, no need to use ITK.

It is nice that you included a small test data set, I was able to test your module using that. A few findings based on these tests:
- The module did not work on Windows. Paths separator on Windows is '\`, therefore this regexp fails (used two different places): `dir_re = r'sub-.+/[a-z]+/'`. A quick fix is to execute `p=p.replace('\\', '/')` for the input path string, but it would be nicer to use pathlib or path handling functions (using regex for getting the parent folder is very fragile).
- Hardcoded paths in cfg file. Why not use application settings? Why not use relative path (within module's resources folder, user home folder, ...)? Conversion failed for me due to the hardcoded paths - I could figure out what's wrong but users would not know why things don't work.
- Report any exceptions, for example by calling logic functions from GUI using:

```
with slicer.util.tryWithErrorDisplay("Some risky operation failed."):
    doSomething()
```

- Ask permission from the user before installing any package (see [example](https://slicer.readthedocs.io/en/latest/developer_guide/script_repository.html#install-a-python-package)).
- Check/uncheck all checkable combobox is really strange. You could replace each combobox with a simple "Check/uncheck all" button.
- Change the module title to be human-readable (use space instead of CamelCase), consider following naming conventions (e.g., data importer modules start with `Import`). For example, the `Import Gifti` module name would be more consistent with the name of similar modules.
- Remember the last selected input folder (it was a bit annoying during testing that I had to reselect the input folder each time I restarted the application or reloaded the module)
- Use ctkPathLineEdit for output folder selection. It makes it easy to copy-paste paths, takes up less space, supports auto-complete, automatic saveing of last selected folder, etc.
- Consider creating closed surface representation for the segmentations to make them visible in 3D.

**Comment by mcespedes99** [comment]
Just updated the code.
**Main changes:**

- The module did not work on Windows. Paths separator on Windows is '`, therefore this regexp fails (used two different places): dir_re = r'sub-.+/[a-z]+/'. A quick fix is to execute p=p.replace('\\', '/') for the input path string, but it would be nicer to use pathlib or path handling functions (using regex for getting the parent folder is very fragile).

> Now I'm using pathlib to find the 2 direct parents of the files (which should correspond to 'datatype' and subject directory, which are used to create output bids folder.

- Hardcoded paths in cfg file. Why not use application settings? Why not use relative path (within module's resources folder, user home folder, ...)? Conversion failed for me due to the hardcoded paths - I could figure out what's wrong but users would not know why things don't work.

> Updated the paths so they can be relative or absolute. Using a relative path to Resources as default.

- Report any exceptions:

> Implemented for main functions in the file.

- Ask permission from the user before installing any package (see [example](https://slicer.readthedocs.io/en/latest/developer_guide/script_repository.html#install-a-python-package)).

> Implemented!

- Check/uncheck all checkable combobox is really strange. You could replace each combobox with a simple "Check/uncheck all" button.

> Done, now using a dynamic button.

- Change the module title to be human-readable (use space instead of CamelCase), consider following naming conventions (e.g., data importer modules start with Import). For example, the Import Gifti module name would be more consistent with the name of similar modules.

> Done.

- Remember the last selected input folder (it was a bit annoying during testing that I had to reselect the input folder each time I restarted the application or reloaded the module)

> Done. It's being saved in the config file now. Only applies for the input folder.

- Use ctkPathLineEdit for output folder selection. It makes it easy to copy-paste paths, takes up less space, supports auto-complete, automatic saveing of last selected folder, etc.

> Done. I had to modify the behaviour a bit as before I was updating the subject list after a change on a directory; however, this was making the package go very slow after I transition to ctkPathLineEdit (specifically, if the user is typing in the path, as the module would try to update the subjects after every character input). Therefore, I added a 'Search subjects' button to allow a more smooth interaction.

- Consider creating closed surface representation for the segmentations to make them visible in 3D.

> No change. I am actually already doing this but only for the segmentations marked as visible.

Let me know if you have any other requests please! Sorry for the delay

**Review by lassoan — APPROVED** [review]
This looks good and all works well. Thank you for your contribution!

**Pull request merged**
